steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/mandorin-be/mandorin-be:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/mandorin-be/mandorin-be:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'images'
      - 'list'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/mandorin-be/mandorin-be'
    entrypoint: 'bash'
    id: 'list_images'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'rmi'
      - '--force'
    entrypoint: 'bash'
    id: 'delete_images'
    waitFor:
      - 'list_images'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mandorin-be'
      - '--image'
      - 'asia-southeast2-docker.pkg.dev/$PROJECT_ID/mandorin-be/mandorin-be:$SHORT_SHA'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
