steps:
  - id: 'build images'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPONAME}/${_IMAGESNAME}:$SHORT_SHA', '.']

  - id: 'push images'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPONAME}/${_IMAGESNAME}:$SHORT_SHA']

  - id: 'deploy images'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICESNAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPONAME}/${_IMAGESNAME}:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

substitutions:
  _REGION: asia-southeast2
  _REPONAME: mandorin-be
  _SERVICESNAME: mandorin-be
  _IMAGESNAME: mandorin-be

options:
  logging: CLOUD_LOGGING_ONLY
